---
title: "Getting set up with R, RStudio, and Git"
format: 
  html:
    toc: true
    toc-depth: 4
---

*We will do this together in class on Wednesday 8/26!*

You first need to choose what computer to setup (you can do multiple if you would like)

- personal computer/laptop (recommended if possible)
- [CI Virtual Labs](http://go.csuci.edu/vdi) (recommended if you don't have a laptop you can configure software on) This allows you to use a web browser and it will look just like if you logged onto a school computer. When Microsoft asks for your email give it you school email, but instead of "@myci.csuci.edu" use "@csuci.edu".
- School computer (Only recommended if you plan to use the same class desktop for homework as well)

## Installing R and RStudio

1. Install [R](https://cran.rstudio.com/).
2. Install [RStudio](https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads).

## Getting setup with Git

3. Make a [GitHub account](https://github.com/). If you already have one you can use it.

4. Provide me with your GitHub user name through this [Google Form](https://docs.google.com/forms/d/e/1FAIpQLScJdWy6xUPBjFu72Ot4iJCR528Epec1xUyZBWdWvmgRN9mkFg/viewform?usp=dialog).

5. Check if you already have Git installed. Macs typically already have it installed. You can check by going to the **Terminal** in RStudio and typing `which git`. 

If it says it does not recognize the command, then you do not have Git installed. Installation differs by operating system, if you have:

- Windows (and CI Virtual Lab), use this link to install [Git](https://gitforwindows.org/).
- Mac, in the Terminal in RStudio enter `git --version`, then `git config`, then accept the offer and click "Install".
- For linux or any issues installing Git follow [this guide](https://happygitwithr.com/install-git#linux) specific to your operating system.

6. Introduce yourself to Git. To do this run each of the following lines of code in the **Console** in RStudio. Make sure to change "Jane Doe" to your GitHub username and "jane@example.org" to the email you used for your GitHub account.

```{r}
#| eval: false

install.packages("usethis")
library(usethis)
use_git_config(user.name = "Jane Doe", user.email = "jane@example.org")
```

## Connecting / Configuring GitHub with your RStudio

7. We need to generate an SSH key in RStudio and then provide it to GitHub. Either follow along with the following setup video, or follow the written steps 7a - 7h.

<center>

<video width="80%" height="45%" align = "center" controls>
  <source src="screencast/00d-ssh-setup.mp4" type="video/mp4">
</video>

</center>

### Generate SSH key

7a. In RStudio click `Tools` then `Global options...`, then navigate to the `Git/SVN` in the left navigation panel.

7b. Click `Create SSH key...` and change `SSH key type` from "ED" to "RSA" then click `Create`.

7c. Now close the popout to navigate back to the `Git/SVN` pane within `Global options`. 

7d. Click `view public key` and copy the generated key to your clipboard. We need to provide this to GitHub online to allow it to interact with Git on our computer.

### Provide GitHub your SSH key

7e. Log in to [GitHub](https://github.com/). 

7f. In the upper right corner click on your profile icon and then click `Settings`.

7g. Click `SSH and GPG keys` from the navigation menu on the left hand side.

7h. Click `New SSH key`. Under `Title` provide a short description to identify you device, such as "my laptop" or "CI Virtual Lab". Under `Key` paste the SSH key you copied from step d. Then click `Add SSH key`.

If you completed all the steps above, congrats you are all done!! If not, please attend an office hour ASAP so we can get you computer set up correctly.
